version: "3.9"
services:
  njs:
    build: ./njs
    # ports:
    #   - "3000:3000"
    environment:
      APP_DOCKER: True
    env_file:
      - ./njs/.env
  rsignals:
    build: ./rsignals
    # ports:
    #   - "8080:8080"
    environment:
      APP_DOCKER: True
